export const FETCH_FULFILLED = 'FETCH_FULFILLED';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_START = 'FETCH_START'

export const FETCH_LOGIN_FULFILLED = 'FETCH_LOGIN_FULFILLED';
export const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED';
export const FETCH_LOGIN_START = 'FETCH_LOGIN_START'


export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN_START = 'USER_LOGIN_START'

export const FETCH_FEED_FULFILLED = 'FETCH_FEED_FULFILLED';
export const FETCH_FEED_FAILED = 'FETCH_FEED_FAILED';
export const FETCH_FEED_START = 'FETCH_FEED_START'

